# Generated by Django 5.1.6 on 2025-03-23 05:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0005_alter_discovery_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discovery',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='discovery',
            name='discovered_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='discovery',
            name='discovery_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discovery',
            name='trivia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
