# Generated by Django 5.1.6 on 2025-03-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0006_alter_discovery_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovery',
            name='image_filename',
            field=models.CharField(default='default.webp', max_length=255),
        ),
    ]
